fujitsu      = RuleSet.where(name: 'Fujitsu'     ).first_or_create
foster_moore = RuleSet.where(name: 'Foster Moore').first_or_create
vodafone     = RuleSet.where(name: 'Vodafone'    ).first_or_create

[
  [fujitsu, 'Activity Log',                    'activity_log'                 ],
  [fujitsu, 'Affected End User Cost Center',   'affected_end_user_cost_center'],
  [fujitsu, 'Affected End User Department',    'affected_end_user_department' ],
  [fujitsu, 'Affected End User Name',          'affected_end_user_name'       ],
  [fujitsu, 'Affected End User Location',      'affected_end_user_location'   ],
  [fujitsu, 'Affected End User Phone',         'affected_end_user_phone'      ],
  [fujitsu, 'Arrival Time',                    'arrival_time'                 ],
  [fujitsu, 'Assignee',                        'assignee'                     ],
  [fujitsu, 'Case Category',                   'case_category'                ],
  [fujitsu, 'Case ID',                         'case_id'                      ],
  [fujitsu, 'Caused By Change',                'caused_by_change'             ],
  [fujitsu, 'Change',                          'change'                       ],
  [fujitsu, 'Change Coordinator',              'change_coordinator'           ],
  [fujitsu, 'Chargeable',                      'chargeable'                   ],
  [fujitsu, 'Child',                           'child'                        ],
  [fujitsu, 'Clarify ID',                      'clarify_id'                   ],
  [fujitsu, 'Classification',                  'classification'               ],
  [fujitsu, 'Closed Time',                     'closed_time'                  ],
  [fujitsu, 'Configuration Item',              'configuration_item'           ],
  [fujitsu, 'Created By',                      'created_by'                   ],
  [fujitsu, 'Cust Ref. Number',                'customer_ref_number'          ],
  [fujitsu, 'Customer Ref Number',             'customer_ref_number'          ],
  [fujitsu, 'Customer Satisfaction Survey',    'customer_satisfaction_survey' ],
  [fujitsu, 'Date of First Transfer',          'date_of_first_transfer'       ],
  [fujitsu, 'Default Severity',                'default_severity'             ],
  [fujitsu, 'Description',                     'description'                  ],
  [fujitsu, 'End User Department',             'end_user_department'          ],
  [fujitsu, 'End User Location',               'end_user_location'            ],
  [fujitsu, 'End User Priority Contact',       'end_user_priority_contact'    ],
  [fujitsu, 'Email Date Receipt',              'email_date_receipt'           ],
  [fujitsu, 'Email Receipt Date/Time',         'email_receipt_date_time'      ],
  [fujitsu, 'External System Ticket',          'external_system_ticket'       ],
  [fujitsu, 'Group',                           'group'                        ],
  [fujitsu, 'Impact',                          'impact'                       ],
  [fujitsu, 'Incident Type',                   'incident_type'                ],
  [fujitsu, 'Last Modified By',                'last_modified_by'             ],
  [fujitsu, 'Last Modified Time',              'last_modified_time'           ],
  [fujitsu, 'Latest Status Change to 3-Hold*', 'latest_status_change_to_hold' ],
  [fujitsu, 'Latest Status Change to Hold*',   'latest_status_change_to_hold' ],
  [fujitsu, 'Logged By',                       'logged_by'                    ],
  [fujitsu, 'Major Incident',                  'major_incident'               ],
  [fujitsu, 'Parent',                          'parent'                       ],
  [fujitsu, 'Planned End Time',                'planned_end_time'             ],
  [fujitsu, 'Planned Start Time',              'planned_start_time'           ],
  [fujitsu, 'Priority',                        'priority'                     ],
  [fujitsu, 'Problem',                         'problem'                      ],
  [fujitsu, 'Recording Method',                'recording_method'             ],
  [fujitsu, 'Reported By',                     'reported_by'                  ],
  [fujitsu, 'Reporting Method',                'reporting_method'             ],
  [fujitsu, 'Requestor',                       'requestor'                    ],
  [fujitsu, 'Resolved By',                     'resolved_by'                  ],
  [fujitsu, 'Resolved Group',                  'resolved_group'               ],
  [fujitsu, 'Resolved Time',                   'resolved_time'                ],
  [fujitsu, 'Resolved User',                   'resolved_user'                ],
  [fujitsu, 'Root Cause',                      'root_cause'                   ],
  [fujitsu, 'Sent to Clarify',                 'sent_to_clarify'              ],
  [fujitsu, 'Severity',                        'severity'                     ],
  [fujitsu, 'Status',                          'status'                       ],
  [fujitsu, 'Summary',                         'summary'                      ],
  [fujitsu, 'Tenant',                          'tenant'                       ],
  [fujitsu, 'Third Party Name',                'third_party_name'             ],
  [fujitsu, 'Third Party Ref.',                'third_party_ref'              ],
  [fujitsu, 'Total Activity Time',             'total_activity_time'          ],
  [fujitsu, 'Type',                            'type'                         ],
  [fujitsu, 'Urgency',                         'urgency'                      ],
  [fujitsu, 'Work Log',                        'work_log'                     ],

  [foster_moore, '3rd Party Ref',               'third_party_ref'            ],
  [foster_moore, 'Approval Flag',               'approval_flag'              ],
  [foster_moore, 'At Task ID',                  'at_task_id'                 ],
  [foster_moore, 'Business Unit Priority',      'business_unit_priority'     ],
  [foster_moore, 'Category',                    'category'                   ],
  [foster_moore, 'Change ID',                   'change_id'                  ],
  [foster_moore, 'Close Code',                  'close_code'                 ],
  [foster_moore, 'Created By',                  'created_by'                 ],
  [foster_moore, 'Created Time',                'created_time'               ],
  [foster_moore, 'Department',                  'department'                 ],
  [foster_moore, 'Description',                 'description'                ],
  [foster_moore, 'DueBy Time',                  'dueby_time'                 ],
  [foster_moore, 'Environment Raised In',       'environment_raised_in'      ],
  [foster_moore, 'Group',                       'group'                      ],
  [foster_moore, 'Impact',                      'impact'                     ],
  [foster_moore, 'Impacted Configuration Item', 'impacted_configuration_item'],
  [foster_moore, 'Impacted Environment',        'impacted_environment'       ],
  [foster_moore, 'Incident Type',               'incident_type'              ],
  [foster_moore, 'Lead Team',                   'lead_team'                  ],
  [foster_moore, 'Managed Service',             'managed_service'            ],
  [foster_moore, 'Priority',                    'priority'                   ],
  [foster_moore, 'Problemid',                   'problemid'                  ],
  [foster_moore, 'Process Area',                'process_area'               ],
  [foster_moore, 'Purchase Order Number',       'purchase_order_number'      ],
  [foster_moore, 'Release Name',                'release_name'               ],
  [foster_moore, 'Request ID',                  'request_id'                 ],
  [foster_moore, 'Request Mode',                'request_mode'               ],
  [foster_moore, 'Request Status',              'request_status'             ],
  [foster_moore, 'Request Status',              'request_status'             ],
  [foster_moore, 'Requester',                   'requester'                  ],
  [foster_moore, 'Resolution Code',             'resolution_code'            ],
  [foster_moore, 'Responded Date',              'responded_date'             ],
  [foster_moore, 'Response DueBy Time',         'response_dueby_time'        ],
  [foster_moore, 'Service Under Warranty',      'service_under_warranty'     ],
  [foster_moore, 'Shared Services',             'shared_services'            ],
  [foster_moore, 'Subcategory',                 'subcategory'                ],
  [foster_moore, 'Subject',                     'subject'                    ],
  [foster_moore, 'Technician',                  'technician'                 ],
  [foster_moore, 'Urgency',                     'urgency'                    ],
  [foster_moore, 'Warranty Decision Notes',     'warranty_decision_notes'    ],

].each do |set, src, out|
  FieldMapping.where(rule_set: set, src_field_name: src).first_or_create(out_field_name: out)
end
