require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FieldMappingsController do

  # This should return the minimal set of attributes required to create a valid
  # FieldMapping. As you add validations to FieldMapping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "rule_set" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FieldMappingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all field_mappings as @field_mappings" do
      field_mapping = FieldMapping.create! valid_attributes
      get :index, {}, valid_session
      assigns(:field_mappings).should eq([field_mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested field_mapping as @field_mapping" do
      field_mapping = FieldMapping.create! valid_attributes
      get :show, {:id => field_mapping.to_param}, valid_session
      assigns(:field_mapping).should eq(field_mapping)
    end
  end

  describe "GET new" do
    it "assigns a new field_mapping as @field_mapping" do
      get :new, {}, valid_session
      assigns(:field_mapping).should be_a_new(FieldMapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested field_mapping as @field_mapping" do
      field_mapping = FieldMapping.create! valid_attributes
      get :edit, {:id => field_mapping.to_param}, valid_session
      assigns(:field_mapping).should eq(field_mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FieldMapping" do
        expect {
          post :create, {:field_mapping => valid_attributes}, valid_session
        }.to change(FieldMapping, :count).by(1)
      end

      it "assigns a newly created field_mapping as @field_mapping" do
        post :create, {:field_mapping => valid_attributes}, valid_session
        assigns(:field_mapping).should be_a(FieldMapping)
        assigns(:field_mapping).should be_persisted
      end

      it "redirects to the created field_mapping" do
        post :create, {:field_mapping => valid_attributes}, valid_session
        response.should redirect_to(FieldMapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved field_mapping as @field_mapping" do
        # Trigger the behavior that occurs when invalid params are submitted
        FieldMapping.any_instance.stub(:save).and_return(false)
        post :create, {:field_mapping => { "rule_set" => "invalid value" }}, valid_session
        assigns(:field_mapping).should be_a_new(FieldMapping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FieldMapping.any_instance.stub(:save).and_return(false)
        post :create, {:field_mapping => { "rule_set" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested field_mapping" do
        field_mapping = FieldMapping.create! valid_attributes
        # Assuming there are no other field_mappings in the database, this
        # specifies that the FieldMapping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FieldMapping.any_instance.should_receive(:update).with({ "rule_set" => "" })
        put :update, {:id => field_mapping.to_param, :field_mapping => { "rule_set" => "" }}, valid_session
      end

      it "assigns the requested field_mapping as @field_mapping" do
        field_mapping = FieldMapping.create! valid_attributes
        put :update, {:id => field_mapping.to_param, :field_mapping => valid_attributes}, valid_session
        assigns(:field_mapping).should eq(field_mapping)
      end

      it "redirects to the field_mapping" do
        field_mapping = FieldMapping.create! valid_attributes
        put :update, {:id => field_mapping.to_param, :field_mapping => valid_attributes}, valid_session
        response.should redirect_to(field_mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the field_mapping as @field_mapping" do
        field_mapping = FieldMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FieldMapping.any_instance.stub(:save).and_return(false)
        put :update, {:id => field_mapping.to_param, :field_mapping => { "rule_set" => "invalid value" }}, valid_session
        assigns(:field_mapping).should eq(field_mapping)
      end

      it "re-renders the 'edit' template" do
        field_mapping = FieldMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FieldMapping.any_instance.stub(:save).and_return(false)
        put :update, {:id => field_mapping.to_param, :field_mapping => { "rule_set" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested field_mapping" do
      field_mapping = FieldMapping.create! valid_attributes
      expect {
        delete :destroy, {:id => field_mapping.to_param}, valid_session
      }.to change(FieldMapping, :count).by(-1)
    end

    it "redirects to the field_mappings list" do
      field_mapping = FieldMapping.create! valid_attributes
      delete :destroy, {:id => field_mapping.to_param}, valid_session
      response.should redirect_to(field_mappings_url)
    end
  end

end
